#include "hw_gpio.h"

//PA 5, 6, 7
//PB 6, 7
void GPIO_SPI1_Init(void)
{
  // --- SCK ---
  LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOA);
  LL_GPIO_InitTypeDef GPIOForSPI;
  GPIOForSPI.Alternate = LL_GPIO_AF_5;
  GPIOForSPI.Mode = LL_GPIO_MODE_ALTERNATE;
  GPIOForSPI.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
  GPIOForSPI.Pin = LL_GPIO_PIN_5;
  GPIOForSPI.Pull = LL_GPIO_PULL_DOWN;
  GPIOForSPI.Speed = LL_GPIO_SPEED_FREQ_HIGH;
  LL_GPIO_Init(GPIOA, &GPIOForSPI);
  
  // --- MISO ---
  GPIOForSPI.Pin = LL_GPIO_PIN_6;
  GPIOForSPI.Pull = LL_GPIO_PULL_UP;
  LL_GPIO_Init(GPIOA, &GPIOForSPI);
  
  // --- MOSI ---
  GPIOForSPI.Pin = LL_GPIO_PIN_7;
  GPIOForSPI.Pull = LL_GPIO_PULL_NO;
  LL_GPIO_Init(GPIOA, &GPIOForSPI);
}

void GPIO_I2C1_Init(void)
{
  LL_AHB1_GRP1_EnableClock(LL_AHB1_GRP1_PERIPH_GPIOB);
  // --- SCL PB6, SDA PB7 ---
  LL_GPIO_InitTypeDef GPIOForI2C1;
  GPIOForI2C1.Alternate = LL_GPIO_AF_4;
  GPIOForI2C1.Mode = LL_GPIO_MODE_ALTERNATE;
  GPIOForI2C1.OutputType = LL_GPIO_OUTPUT_OPENDRAIN;
  GPIOForI2C1.Pin = LL_GPIO_PIN_6 | LL_GPIO_PIN_7;
  GPIOForI2C1.Pull = LL_GPIO_PULL_UP;
  GPIOForI2C1.Speed = LL_GPIO_SPEED_FREQ_HIGH;
  LL_GPIO_Init(GPIOB, &GPIOForI2C1);
}
